# Generated by Django 5.1 on 2025-02-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email_address',
            field=models.EmailField(default='hr@fresher.com', max_length=254),
        ),
    ]
