# Generated by Django 5.1 on 2025-02-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_job_logo_job_required_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='required_education',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
    ]
