# Generated by Django 5.1 on 2025-02-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancy_total',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
