# Generated by Django 5.1 on 2025-02-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_job_vacancy_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
    ]
