# Generated by Django 5.1 on 2025-03-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_certification_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
